version: '3.8'

services:
  camera-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CAMERA_IP=192.168.1.102
      - CAMERA_USERNAME=manuco
      - CAMERA_PASSWORD=manu0625
    restart: unless-stopped
    volumes:
      - ./snapshots:/app/snapshots
    networks:
      - camera-network

networks:
  camera-network:
    driver: bridge 